### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by hazarek** [sbarex/QLMarkdown#40]
v 1.0 (14)
CRASH - Download and try this file, copy-paste into QLMarkdown window ->  https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md or https://gist.github.com/rxaviers/7360908

my setings;
<img width="956" alt="Ekran Resmi 2020-01-03 23 44 21" src="https://user-images.githubusercontent.com/36481442/103488466-bb666480-4e1d-11eb-803a-71504118e861.png">
<img width="431" alt="Ekran Resmi 2020-01-03 23 44 26" src="https://user-images.githubusercontent.com/36481442/103488470-c0c3af00-4e1d-11eb-9341-29195a3625e9.png">

**Comment by hazarek** [comment]
"emoji as image" works.

Also TOC heads are extremely slow.->  https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md

**Comment by sbarex** [comment]
The emoji bug is fixed in last commit.
The slow scroll from links is the same problem of #27.

Quicklook do not allow first view responder. When you click to a link the log show a warning about this problem.
I have created a repository with all discovery quicklook bugs: https://github.com/sbarex/QLTest

For anchor headers I saw that the `&` character is omitted to generate the anchor. @hazarek do you know a documentation page explaining which characters are not allowed? Do you also see the bug #39?

**Comment by hazarek** [comment]
>  @hazarek do you know a documentation page explaining which characters are not allowed? Do you also see the bug #39?

No, I don't know.

> (is not required to copy/paste the test code in the editor, on file menu there is a command to open a .md file, or you can drag the file and drop over the editor).

Thanks, i didn't notice
